//백망되
/*
        <meta property="og:url" content="https://ridibooks.com/books/875103701"/>
        <meta property="og:title" content="백작가의 망나니가 되었다"/>
        <link rel="canonical" href="https://ridibooks.com/books/875103701"/>
*/
var book = {
                "id": "875103701",
                "seriesId": "875103701",
                "genre": "fantasy",
                "subGenre": "fantasy_serial",
                "discountStartDate": null,
                "discountEndDate": null,
                "isCashback": false,
                "isRentalOnly": false,
                "isSeriesGrouping": true
            };

var bookDetail = {
                "id": "875103701",
                "title": "백작가의 망나니가 되었다 1화",
                "web_title": "",
                "sub_title": "",
                "author": "유려한",
                "translator": "",
                "authors": {
                    "author": {
                        "95088": "유려한"
                    }
                },
                "authors_simple": {
                    "95088": "유려한"
                },
                "authors_count": 1,
                "pub_id": "875",
                "publisher": "도서출판 청어람",
                "grade": "4.8",
                "grade_count": "7791",
                "review_display_id": null,
                "review_count": "1952",
                "age_limit": "0",
                "description": "<b>&lt;책소개&gt;<\/b>\n\n눈을 떠보니 소설 속이었다.\r\n그것도 망나니로 유명한 백작가 도련님 몸으로.\r\n\r\n하지만,\r\n그렇다고 망나니가 될 순 없잖아?\n\n\n<b>&lt;저자 소개&gt;<\/b>\n\n유려한",
                "volume": "1",
                "is_buy": "1",
                "filesize": "486",
                "format_ver": "epub",
                "pub_date": "20181002",
                "reg_date": "20181002000057",
                "open_date": "2018-10-02 00:00:58",
                "is_open": "1",
                "is_trial": false,
                "is_adult_only": false,
                "preview_rate": "10",
                "category": "1752",
                "category2": "0",
                "parent_category": "1750",
                "genre": "fantasy",
                "genre2": "",
                "sub_genre": "fantasy_serial",
                "sub_genre2": "general",
                "genre_name": "판타지 e북",
                "genre2_name": "",
                "category_name": "퓨전 판타지",
                "category_name2": "미정",
                "is_magazine": false,
                "is_novel": false,
                "has_category_use_series": "1",
                "series_cover_b_id": "875177449",
                "price_info": {
                    "current_price": "0",
                    "regular_price": 0,
                    "paper_price": 0,
                    "discount_percentage": 0,
                    "ebook_discount_percentage": 0,
                    "is_buy_available": true,
                    "rental_price": null,
                    "ebook_rent_regular_price": 0,
                    "rental_term": null,
                    "rental_discount_percentage": 0,
                    "is_rental_only": false,
                    "is_rental_available": false,
                    "is_flatrate_available": false,
                    "flatrate_id": null,
                    "is_cashback_period": false,
                    "cashback_period_str": null,
                    "is_rent_pointback": false,
                    "rent_pointback_amount": 0,
                    "is_restricted_buy": false,
                    "is_restricted_rent": false,
                    "discount_start_date": null,
                    "discount_end_date": null
                },
                "series_price_info": {
                    "series_id": "875103701",
                    "book_count": "1272",
                    "free_book_count": "25",
                    "flatrate_id": null,
                    "min_nonzero_price": "100",
                    "min_price": "0",
                    "max_price": "100",
                    "total_regular_price": "124700",
                    "regular_price": "124700",
                    "regular_price_discount_rate": 0,
                    "total_price": "124700",
                    "entire_purchase_discount_price": "124700",
                    "entire_purchase_discount_rate": 0,
                    "min_nonzero_rental_price": null,
                    "min_rental_price": null,
                    "max_rental_price": null,
                    "total_rental_price": null,
                    "entire_rental_discount_rate": null,
                    "entire_rental_discount_price": null,
                    "rental_term": null,
                    "entire_rental_term": null
                },
                "price": "0",
                "is_rental": "0",
                "series_id": "875103701",
                "series_title": "백작가의 망나니가 되었다",
                "is_series": "1",
                "is_series_complete": "0",
                "series_grade": "4.8",
                "series_grade_count": "7791",
                "series_unit": "화",
                "is_serial": "1",
                "is_wait_free": true,
                "use_series_grouping": true,
                "is_setbook": false,
                "link_book_count": "0",
                "kpc_id": "",
                "rank": null,
                "is_new_book": null,
                "comic_is_manga": "0",
                "comic_has_blank": "0",
                "comic_is_hd": "0",
                "comic_is_webtoon": "0",
                "is_comic": "0",
                "setbook_policy": "0",
                "rental_price": null,
                "rental_term": null,
                "is_support_ios": true,
                "is_support_android": true,
                "is_support_windows": true,
                "is_support_mac": true,
                "is_support_paper": true,
                "is_available_on_pc": true,
                "is_available_on_web_viewer": true,
                "is_kpc_book": false,
                "remain_quantity": null,
                "user_book": {
                    "b_id": "875103701",
                    "u_id": "lys0star",
                    "service_type": "normal",
                    "status": "NEW",
                    "is_readable": true,
                    "reg_date": null,
                    "rental_period": null,
                    "remaining_rental_period": "7979년 276일 남음",
                    "expired": false,
                    "expire_date": "9999-12-31 23:59:59"
                },
                "reading_note": null,
                "property_info": {
                    "num_chars": 424,
                    "num_pages": null,
                    "paper_pub_date": null,
                    "preview_generated": null,
                    "related_serial_book_start": null,
                    "related_serial_book_end": null,
                    "is_somedeal": null,
                    "paper_buy_regular_price": null,
                    "ebook_rent_regular_price": null,
                    "ebook_buy_regular_price": 0,
                    "cashback_period_end": null,
                    "cashback_period_start": null,
                    "discount_period_end": null,
                    "discount_period_start": null,
                    "ridi_open_date": "2018-10-02 00:00:58"
                }
            };