
            var Ridi = Ridi || {};
            Ridi.Auth = true;
            Ridi.Platform = 'pc';
            Ridi.globals = {
                isLoggedIn: true,
                userIdx: 4543796,
                isVerifiedAdult: true,
                isAdultVerifyExpired: false,
                ruid: '4eb82d27-ruid-46da-8766-d897fe1dfa61',
                isPc: true,
                isTablet: false,
                isMobile: false,
                isAndroid: false,
                isIos: false,
                isPaper: false,
                isPaperPro: false,
                isRidiApp: false,
                ridiAppTheme: '',
                ridiAppVersion: null,
                isNotUseNotificationCenter: false,
                apiUrl: 'https://api.ridibooks.com',
                notificationApiUrl: 'https://notification-api.ridibooks.com/notification',
                apiToken: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiJseXMwc3RhciIsInVfaWR4Ijo0NTQzNzk2LCJleHAiOjE3NTI4MTY4OTl9.d6lKzua_71hDg0AVGMH7SKZjEchMlmysfFqF7gQFo28',
                sslHostLink: 'https://ridibooks.com',
                staticUrl: 'https://static.ridicdn.net/books-backend/p/9a9308',
                miscUrl: '//img.ridicdn.net',
                welcomeMessage: '',
                readingDataApiBaseUrl: 'https://reading-data-api.ridibooks.com',
                bookApiUrl: 'https://book-api.ridibooks.com',
                accountApiUrl: 'https://account.ridibooks.com',
                oauth2_client_id: 'ePgbKKRyPvdAFzTvFg2DvrS7GenfstHdkQ2uvFNd',
                webViewerUrl: '//view.ridibooks.com/books/',
                isDoublePointDay: false,
            };